# the tag "version" is obsolete and can be removed on newer versions
# version: "3.9"

services:
  ns3:
    image: ns3-nbiot
    build:
      context: .
    container_name: ns3-nbiot
    working_dir: /opt/ns3-nbiot
    volumes:
      - ./ns3-nbiot:/ns3-nbiot
      - ./logs:/opt/ns3-nbiot/logs
    stdin_open: true
    tty: true
